library(dplyr)
library(readr)

read_csv(file="../ipdln_hackathon_2018_data/ipdln_synth_final.csv") %>%
mutate(abderr = factor(ABDERR_synth, levels = 1:2, labels = c("Aboriginal", "Non-aboriginal")),
       abident = factor(ABINDENT_synth, levels = 1:6, labels = c("North American Indian single response",
                                                                  "Métis single response",  
                                                                  "Inuit single response", 
                                                                  "Multiple Aboriginal identity responses", 
                                                                  "Aboriginal responses not included elsewhere", 
                                                                  "Non-Aboriginal identity population"),
       adifclty = factor(ADIFCLTY_synth, levels = 1:4, labels = c("No", 
                                                                  "Not stated", 
                                                                  "Yes, often",  
                                                                  "Yes, sometimes"),
       age_imm_revised = factor(AGE_IMM_REVISED_group_synth, levels = 1:9, labels = c("< 5 yrs", 
                                                                                      " 5 -  9 yrs", 
                                                                                      "10 - 14 yrs",  
                                                                                      "15 - 19 yrs",  
                                                                                      "20 - 24 yrs",  
                                                                                      "25 - 29 yrs",  
                                                                                      "30 - 34 yrs",  
                                                                                      "35 - 39 yrs",  
                                                                                      "40 - 44 yrs",  
                                                                                      "45 - 49 yrs",  
                                                                  "50 - 54 yrs",  
                                                                  "55 - 59 yrs",  
                                                                  "60+ yrs",
                                                                  "Non-permanent residents",
                                                                  "Non-immigrants and institutional residents")),
       citsm = factor(CITSM_synth, levels=1:2, labels=c("Canadian citizen by birth", "Not a Canadian citizen by birth")),
       cod1 = factor(COD1_synth, levels=1:5, labels=c("Communicable, maternal, perinatal, and nutritional conditions",
                                                       "Noncommunicable diseases", 
                                                       "Injuries", 
                                                       "Other causes of death or cause of death not available", 
                                                       "Did not die")),
       cod2 = factor(COD2_synth, levels=1:14, labels=c("Infectious and parasitic diseases",
                                                        "Respiratory infections",
                                                        "Colon and rectal cancers",
                                                        "Female Breast cancer",
                                                        "Diabetes mellitus",
                                                        "Alzheimer’s disease and other dementias",
                                                        "Ischemic heart disease", 
                                                        "Cerebrovascular disease", 
                                                        "Respiratory diseases", 
                                                        "Digestive diseases", 
                                                        "Genitourinary diseases", 
                                                        "Unintentional injuries", 
                                                        "Other causes of death or cause of death not available",
                                                        "Did not die")),
       cowd = factor(COWD_synth, levels=1:7, labels=c(
                                        "Unpaid family workers - Worked without pay for a relative in a family business or farm",
                                        "Paid worker - Originally self-employed without paid help, incorporated",
                                        "Paid worker - Originally self-employed with paid help, incorporated",
                                        "Paid Worker - Working for wages, salary, tips or commission",
                                        "Self-employed without paid help, not incorporated",
                                        "Self-employed with paid help, not Incorporated",
                                        "Not applicable")),
      disabfl = factor(DISABFL_synth, levels=1:4, labels=c("No", 
                                                            "Not stated", 
                                                            "Yes, often", 
                                                            "Yes, sometimes")),
      disabil = factor(DISABIL_synth, levels=1:17, labels=c(
            "Difficulty with daily activities & activities reduced at home and in other activities",
            "Difficulty with daily activities & activities reduced at home and at work/school",
            "Difficulty with daily activities & activities reduced at home at work/school and in other activities",
            "Difficulty with daily activities & activities reduced at work/school and in other activities",
            "Difficulty with daily activities & activities reduced at home",
            "Difficulty with daily activities & activities reduced in other activities",
            "Difficulty with daily activities & activities reduced at work/school",
            "Difficulty with daily activities", 
            "No difficulty with daily activities and no reduced activities",
            "Activities reduced at home and in other activities",
            "Activities reduced at home and at work/school",
            "Activities reduced at home, at work/school and in other activities",
            "Activities reduced at work/school and in other activities",
            "Activities reduced at home",
            "Activities reduced in other activities", 
            "Activities reduced at work/school",
            "Not stated )),
      dpob11n = factor(DPOB11N_synth, levels=1:10, labels=c(
                      "Non-immigrant",
                      "Latin America and Caribbean", 
                      "Western Europe",
                      "Eastern Europe",
                      "Sub-Saharan Africa",	
                      "North Africa, South West Asia, Middle East",
                      "South Asia",
                      "Southeast Asia",
                      "East Asia (incl Singapore)",
                      "Australia, New Zealand, Oceania, Greenland")), 
      dvismin = factor(DVISMIN_synth, levels=1:10, labels=c(
                      "Chinese", 
                      "South Asian", 
                      "Black",
                      "Filipino", 
                      "Latin American", 
                      "Southeast Asian", 
                      "Arab", 
                      "West Asian", 
                      "Korean", 
                      "Japanese", 
                      "Visible minority, n.i.e.", 
                      "Multiple visible minority",
                      "Aboriginal self-reporting",
                      "Not a visible minority")),
      efcnt_pp_revised = factor(EFCNT_PP_REVISED_synth, levels=1:10, labels=c(
                      " 1 person", 
                      " 2 family members", 
                      " 3 family members", 
                      " 4 family members",
                      " 5 family members", 
                      " 6 family members", 
                      " 7 family members",
                      " 8 family members",
                      " 9 family members",
                      "10 or more family members")),
      fol = factor(FOL_synth, levels=1:4, labels=c(
                    "English", 
                    "French",
                    "English and French", 
                    "Neither English nor French")), 
      fptim = factor(FPTIM_synth, levels=1:3, labels=c("Worked mainly full-time weeks", 
                                                        "Worked mainly part-time weeks", 
                                                        "Not applicable (didn’t work)")),
      genstpob = factor(GENSTPOB_synth, levels=1:3, labels=c(
                        "1st generation - Respondent born outside Canada",
                        "2nd generation - Respondent born in Canada of at least one foreign-born parent",
                        "3rd generation - Respondent born in Canada and both parents born in Canada")),
      hcdd = factor(HCDD_synth, levels=1:13, labels=c(
                      "None",
                      "High school graduation certificate or equivalency certificate",
                      "Other trades certificate or diploma",
                      "Registered apprenticeship certificate",
                      "College, CEGEP or other non-university certificate or diploma from a program of 3 months to less than 1 year",
                      "College, CEGEP or other non-university certificate or diploma from a program of 1 year to 2 years",
                      "College, CEGEP or other non-university certificate or diploma from a program of more than 2 years",
                      "University certificate or diploma below bachelor level",
                      "Bachelor's degree",
                      "University certificate or diploma above bachelor level",
                      "Degree in medicine, dentistry, veterinary medicine or optometry",
                      "Master's degree",
                      "Earned doctorate degree")),
      immder = factor(IMMDER_synth, levels=1:3, labels=c("Immigrants", 
                                                        "Non-permanent residents",
                                                        "Non-immigrants")),
      kid_group = factor(KID_group_synth, levels=1:3, labels=c(
                                                        "No children",
                                                        "One or two children",
                                                        "Three or more children")),
      loinca = factor(LOINCA_synth, levels=1:3, labels=c(
                                                        "Non-low income", 
                                                        "Low income",
                                                        "Concept not applicable")),
      loincb = factor(LOINCA_synth, levels=1:3, labels=c(
                                                        "Non-low income",
                                                        "Low income",
                                                        "Concept not applicable")),
      marst = factor(MARST_synth, levels=1:5, labels=c(
                                                        "Divorced",
                                                        "Legally married (and not separated)" 
                                                        "Separated, but still legally married",
                                                        "Never legally married (single)",
                                                        "Widowed")),
      nocsbrd = factor(NOCSBRD_synth, levels=1:5, labels=c(





                 
       ) -> hd


,
col_types=cols(
  ABDERR_synth = parse_factor(c("1","2"), levels = c("Aboriginal", "Non-aboriginal")),
  ABIDENT_synth = col_integer(),
  ADIFCLTY_synth = col_integer(),
  CITSM_synth = col_integer(),
  COWD_synth = col_integer(),
  DISABFL_synth = col_integer(),
  DISABIL_synth = col_integer(),
  DVISMIN_synth = col_integer(),
  FOL_synth = col_integer(),
  FPTIM_synth = col_integer(),
  GENSTPOB_synth = col_integer(),
  HCDD_synth = col_integer(),
  IMMDER_synth = col_integer(),
  LOINCA_synth = col_integer(),
  LOINCB_synth = col_integer(),
  MARST_synth = col_integer(),
  NOCSBRD_synth = col_integer(),
  OLN_synth = col_integer(),
  POBDER_synth = col_integer(),
  SEX_synth = col_integer(),
  TRMODE_synth = col_integer(),
  RPAIR_synth = col_integer(),
  PR_synth = col_integer(),
  RUINDFG_synth = col_integer(),
  d_licoratio_da_bef_synth = col_integer(),
  S_DEAD_synth = col_integer(),
  EFCNT_PP_R_synth = col_integer(),
  AGE_IMM_R_group_synth = col_integer(),
  COD1_synth = col_integer(),
  COD2_synth = col_integer(),
  DPOB11N_synth = col_integer(),
  KID_group_synth = col_integer(),
  YRIM_group_synth = col_integer(),
  age_group_synth = col_integer()
)               
)

